Fix: `make terraform` broken with STS credentials
Regression from 3df8a298fcd4297a91f5c34ddce6cd94ec3b9449.

```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws.us-east-1: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider
```