Fix: Worker fails due to read-only file system
OSError: [Errno 30] Read-only file system: '/home/sbx_user1068'

Regression from 396b4c42d816c4837034c350dfcb23676d419da5